# Generated by Django 3.0.4 on 2020-04-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('producer', models.CharField(max_length=255, null=True)),
                ('year', models.CharField(max_length=4, null=True)),
            ],
        ),
    ]
