# Generated by Django 3.0.4 on 2020-04-13 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='feedback',
        ),
    ]
